import { ExternalData, InternalData } from "../types"

// the ID parameter should be ommited, here is just because im not using any DB connection
// but in a real app, there id is the id generated by the DB
export const mapExternalToInternal = ({ externalData, id }: { externalData: ExternalData, id: number }): InternalData => {
	return {
		id,
		externalId: externalData.id,
		name: externalData.name,
		abilities: [{
			name: externalData.abilities[0].ability.name,
			isHidden: externalData.abilities[0].is_hidden
		}]
	}
}